# Generated by Django 5.2.16 on 2026-07-24 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='purchase_requests/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Form dosyası')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='İşletme adı')),
                ('authorized_person', models.CharField(blank=True, max_length=200, verbose_name='Yetkili personel')),
                ('form_date', models.DateField(blank=True, null=True, verbose_name='Form tarihi')),
                ('form_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Form numarası')),
                ('status', models.CharField(choices=[('UPLOADED', 'Yüklendi'), ('PROCESSING', 'İşleniyor'), ('REVIEW_REQUIRED', 'Kontrol gerekli'), ('APPROVED', 'Onaylandı'), ('FAILED', 'Hata oluştu')], default='UPLOADED', max_length=30, verbose_name='İşlem durumu')),
                ('raw_ocr_text', models.TextField(blank=True, verbose_name='Ham OCR metni')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='Çıkarılan yapılandırılmış veri')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Satın alma talebi',
                'verbose_name_plural': 'Satın alma talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
