# Generated by Django 5.2.16 on 2026-07-24 13:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(verbose_name='Satır numarası')),
                ('raw_product_name', models.CharField(blank=True, max_length=300, verbose_name='OCR tarafından okunan ürün adı')),
                ('product_name', models.CharField(blank=True, max_length=300, verbose_name='Düzeltilmiş ürün adı')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Birim')),
                ('week1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='1. hafta')),
                ('week2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='2. hafta')),
                ('week3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='3. hafta')),
                ('week4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='4. hafta')),
                ('week5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='5. hafta')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Güven skoru')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('VALID', 'Geçerli'), ('REVIEW_REQUIRED', 'Kontrol gerekli'), ('INVALID', 'Geçersiz')], default='PENDING', max_length=30, verbose_name='Satır durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requests_app.purchaserequest', verbose_name='Bağlı olduğu form')),
            ],
            options={
                'verbose_name': 'Talep satırı',
                'verbose_name_plural': 'Talep satırları',
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('purchase_request', 'row_number'), name='unique_request_row_number')],
            },
        ),
    ]
