# Generated by Django 5.2.16 on 2026-07-27 06:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_purchaserequestline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_item_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SAP kalem kodu')),
                ('item_name', models.CharField(max_length=300, verbose_name='Ürün adı')),
                ('normalized_name', models.CharField(blank=True, db_index=True, editable=False, max_length=300, verbose_name='Standartlaştırılmış ürün adı')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Birim')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['item_name'],
            },
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='matching_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Eşleştirme güveni'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='matching_method',
            field=models.CharField(choices=[('NONE', 'Yöntem yok'), ('EXACT_NAME', 'Tam ürün adı'), ('ALIAS', 'Alternatif ürün adı'), ('FUZZY', 'Benzer metin'), ('MANUAL', 'Kullanıcı seçimi')], default='NONE', max_length=30, verbose_name='Eşleştirme yöntemi'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='matching_status',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Henüz eşleştirilmedi'), ('MATCHED', 'Eşleştirildi'), ('REVIEW_REQUIRED', 'Eşleşme kontrolü gerekli'), ('NOT_MATCHED', 'Eşleşme bulunamadı')], default='NOT_PROCESSED', max_length=30, verbose_name='Eşleştirme durumu'),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='requests_app.product', verbose_name='Eşleşen katalog ürünü'),
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=300, verbose_name='Alternatif ürün adı')),
                ('normalized_alias', models.CharField(blank=True, db_index=True, editable=False, max_length=300, verbose_name='Standartlaştırılmış alternatif ad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='requests_app.product', verbose_name='Bağlı ürün')),
            ],
            options={
                'verbose_name': 'Ürün alternatif adı',
                'verbose_name_plural': 'Ürün alternatif adları',
                'ordering': ['alias_name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'normalized_alias'), name='unique_product_normalized_alias')],
            },
        ),
    ]
