# Generated by Django 5.2.16 on 2026-07-28 12:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_purchaserequest_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Birleştirme adı')),
                ('status', models.CharField(choices=[('READY', 'Hazır'), ('EXPORTED', 'Dışa aktarıldı'), ('SENT_TO_SAP', 'SAP sistemine aktarıldı')], default='READY', max_length=30, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme zamanı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consolidation_batches', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Talep birleştirmesi',
                'verbose_name_plural': 'Talep birleştirmeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme zamanı')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='requests_app.consolidationbatch', verbose_name='Birleştirme')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_source', to='requests_app.purchaserequest', verbose_name='Kaynak talep formu')),
            ],
            options={
                'verbose_name': 'Birleştirme kaynak formu',
                'verbose_name_plural': 'Birleştirme kaynak formları',
                'ordering': ['purchase_request_id'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30, verbose_name='Birim')),
                ('week1', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='1. hafta')),
                ('week2', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='2. hafta')),
                ('week3', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='3. hafta')),
                ('week4', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='4. hafta')),
                ('week5', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='5. hafta')),
                ('source_request_count', models.PositiveIntegerField(default=0, verbose_name='Kaynak form sayısı')),
                ('source_line_count', models.PositiveIntegerField(default=0, verbose_name='Kaynak satır sayısı')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requests_app.consolidationbatch', verbose_name='Birleştirme')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_lines', to='requests_app.product', verbose_name='Katalog ürünü')),
            ],
            options={
                'verbose_name': 'Birleştirilmiş ürün satırı',
                'verbose_name_plural': 'Birleştirilmiş ürün satırları',
                'ordering': ['product__item_name'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'product'), name='unique_product_per_consolidation_batch')],
            },
        ),
    ]
