# Generated by Django 5.2.16 on 2026-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_consolidationbatch_consolidationsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_doc_entry',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SAP DocEntry'),
        ),
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_doc_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SAP belge numarası'),
        ),
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_error_message',
            field=models.TextField(blank=True, default='', verbose_name='SAP hata mesajı'),
        ),
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_request_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='SAP istek verisi'),
        ),
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_response_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='SAP cevap verisi'),
        ),
        migrations.AddField(
            model_name='consolidationbatch',
            name='sap_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="SAP'ye gönderilme zamanı"),
        ),
    ]
